services:

  popcorn_db:
    image: postgres:latest
    container_name: popcorn_db
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: popcornegott
      POSTGRES_DB: popcorn
      POSTGRES_USER: popcorn
    networks:
      - db_bridge
    ports:
      - 5432:5432
  
networks:
  db_bridge:
    driver: bridge