services:

  popcorn_db:
    image: postgres:latest
    container_name: popcorn_db
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: popcornegott
      POSTGRES_DB: popcorn
      POSTGRES_USER: popcorn
    networks:
      - db_bridge
    ports:
      - 5432:5432
  
  popcorn_app:
    image: popcorn_app
    container_name: popcorn_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - db_bridge
    ports:
      - 8501:8501
    depends_on:
      - popcorn_db
    command: gunicorn dash_app:server --bind 0.0.0.0:8501 --workers 4

networks:
  db_bridge:
    driver: bridge